# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:
    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [723]:
import numpy as np

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [724]:
# YOUR CODE HERE
my_array1 = np.array([1,42,36,2,4],dtype=int)

#Printing array, shape and data type
print(my_array1)
print(my_array1.shape)
print(my_array1.dtype)

my_array2=np.array([1,3,6,'Berkeley',7,'Data'])
print(my_array2)
print(my_array2.shape)
print(my_array2.dtype)
'''my_array2 contains both interger and string data type. 
When NumPy encounters this mix of data types, it assigns the dtype '<U11' to the array, 
which indicates Unicode strings of length up to 11 characters.
The integers are implicitly converted to strings to maintain 
homogeneity within the array.'''

[ 1 42 36  2  4]
(5,)
int32
['1' '3' '6' 'Berkeley' '7' 'Data']
(6,)
<U11


"my_array2 contains both interger and string data type. \nWhen NumPy encounters this mix of data types, it assigns the dtype '<U11' to the array, \nwhich indicates Unicode strings of length up to 11 characters.\nThe integers are implicitly converted to strings to maintain \nhomogeneity within the array."

---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [725]:
# YOUR CODE HERE
my_array3=np.array([[1,3,6],[2,4,8]])

print(my_array3)
print(my_array3.shape)
print(my_array3.dtype)
print(my_array3.size)

##The size represents the total number of elements in the array

[[1 3 6]
 [2 4 8]]
(2, 3)
int32
6


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [726]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
#creating array with random data with given inputs
tabular_data = np.random.random((num_samples, num_features))

print("Shape of tabular data:", tabular_data.shape)

print("First few rows of tabular data:")
print(tabular_data[:3])

Shape of tabular data: (100, 17)
First few rows of tabular data:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
  3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
  2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01
  4.17304802e-01]
 [5.58689828e-01 1.40386939e-01 1.98101489e-01 8.00744569e-01
  9.68261576e-01 3.13424178e-01 6.92322616e-01 8.76389152e-01
  8.94606664e-01 8.50442114e-02 3.90547832e-02 1.69830420e-01
  8.78142503e-01 9.83468338e-02 4.21107625e-01 9.57889530e-01
  5.33165285e-01]
 [6.91877114e-01 3.15515631e-01 6.86500928e-01 8.34625672e-01
  1.82882773e-02 7.50144315e-01 9.88861089e-01 7.48165654e-01
  2.80443992e-01 7.89279328e-01 1.03226007e-01 4.47893526e-01
  9.08595503e-01 2.93614148e-01 2.87775339e-01 1.30028572e-01
  1.93669579e-02]]


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [727]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
image_data = np.random.random((num_rows, num_cols, num_images, num_channels))

print("Shape of image data:", image_data.shape)

print(image_data)

Shape of image data: (256, 256, 100, 3)
[[[[0.25789298 0.93444549 0.61911963]
   [0.98544491 0.03264387 0.72516666]
   [0.56555424 0.49242405 0.25921813]
   ...
   [0.44789892 0.56178626 0.73671096]
   [0.79648887 0.44750814 0.18412756]
   [0.82873285 0.03099796 0.94672827]]

  [[0.57697785 0.87538874 0.60856544]
   [0.25165958 0.29612992 0.53292256]
   [0.96207821 0.1844956  0.50989838]
   ...
   [0.54207615 0.82517533 0.03198418]
   [0.87796042 0.034634   0.69319456]
   [0.58748448 0.64174918 0.37408019]]

  [[0.27546203 0.50940858 0.88582312]
   [0.56528967 0.66314889 0.44137923]
   [0.97213909 0.74252245 0.35490251]
   ...
   [0.27263228 0.48148581 0.19203127]
   [0.84711292 0.50337761 0.52716018]
   [0.28807959 0.51199923 0.00196365]]

  ...

  [[0.79810122 0.39137359 0.82888711]
   [0.90491256 0.57452732 0.41914582]
   [0.33724212 0.74840502 0.96197697]
   ...
   [0.314589   0.52017255 0.88902661]
   [0.96497054 0.23189635 0.81425845]
   [0.07250641 0.65411548 0.32837903]]

  [[0

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [728]:
# YOUR CODE HERE
my_array4=np.array([[1,3],[2,4],[5,9]])
print("Shape of the array:",my_array4.shape)
print("Sum of all elements:",my_array4.sum())
print("Sum of all elements by column:",my_array4.sum(axis=0))
print("Sum of all elements by row with float elements",my_array4.sum(axis=1,dtype=float))
print("First row of array:",my_array4[0])
print("Second row of array:",my_array4[1])
print("Element at position (1,0):",my_array4[1,0])

my_array4[2,1]=10
print("Array with modified (2,1) position",my_array4)

for row in my_array4:
    for element in row:
        print(element)



Shape of the array: (3, 2)
Sum of all elements: 24
Sum of all elements by column: [ 8 16]
Sum of all elements by row with float elements [ 4.  6. 14.]
First row of array: [1 3]
Second row of array: [2 4]
Element at position (1,0): 2
Array with modified (2,1) position [[ 1  3]
 [ 2  4]
 [ 5 10]]
1
3
2
4
5
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) empty numpy array
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [729]:
# YOUR CODE HERE
print("(3,2) array with pixel between 0 and 1:",np.random.random((3,2)))
print("Array representing years from 1991 to 2017:",np.linspace(1991,2017,27,dtype=int))
#print("Empty (3,5,10) array:",np.empty((3,5,10)))

empty_array = np.empty((3, 5, 10))
print("Empty (3, 5, 10) array:", empty_array)

ones_array=np.ones((3,5,10),dtype=int)
print("(3,5,10) array of ones:",ones_array)

print("Array with constant value (5):",ones_array*5)

sample_size = 10
random_array = np.random.normal(loc=0, scale=1, size=sample_size)

print("Array with random numbers drawn from a normal distribution:",random_array)

(3,2) array with pixel between 0 and 1: [[0.28999571 0.50818013]
 [0.47655793 0.57281228]
 [0.53403895 0.66869277]]
Array representing years from 1991 to 2017: [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Empty (3, 5, 10) array: [[[6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310]
  [6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310]
  [6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310]
  [6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310 6.95335215e-310 6.95335215e-310
   6.95335215e-310 6.95335215e-310

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [730]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [731]:
# YOUR CODE HERE

#Creating 3 nested arrays with each of size (3,3)
years_3d = years.reshape((3,3,3))
print("3 nested arrays of size (3,3):",years_3d)

#Converting years_3D array to a flat 1D array
years_1d=years_3D.flatten()
print("1D flattened array:",years_1d)

#Adding a new axis in front
years_2d = np.expand_dims(years_1d, axis=0)
print("Shape of the array with a new axis:", years_2d.shape)

#Removing the axis (front axis)
years_1d = years_2d.squeeze(axis=0)

# Printing the shape of the array after removing the first axis
print("Shape of the array after removing the first axis:", years_1d.shape)

3 nested arrays of size (3,3): [[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
1D flattened array: [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of the array with a new axis: (1, 27)
Shape of the array after removing the first axis: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [796]:
# YOUR CODE HERE

#Five examples of np.concatenate()
arr1 = np.array([[3, 6], [7, 4]])
arr2 = np.array([[2, 4], [1, 5]])

result1 = np.concatenate((arr1, arr2), axis=0)
print("Concatenated array along rows:", result1)

result2=np.concatenate((arr1,arr2),axis=1)
print("Concatenated array along columns:",result2)

result3 = np.concatenate((arr1, arr2))
print("Concatenated array by default:",result3)

arr3 = np.array([[1, 2]])
result4 = np.concatenate((arr1, arr2, arr3),axis=None)
print("Concatenated array of different shape:", result4)

arr4=np.array([[7],[0]])
result5=np.concatenate((arr1,arr3,arr4),axis=None)
print("Concatenated array of different shape:", result5)


#Four examples of np.stack()
arr1_stack = np.array([1, 2, 3])
arr2_stack = np.array([4, 5, 6])

stack1_result = np.stack((arr1_stack, arr2_stack))
print("Stacking two 1D arrays vertically:", stack1_result)

stack2_result = np.stack((arr1_stack, arr2_stack),axis=1)
print("Stacking two 1D arrays horizontally:", stack2_result)

stack3_result = np.stack((arr1, arr2))
print("Stacking two 2D arrays along a new axis:", stack3_result)

stack4_result = np.stack((arr1, arr2),axis=1)
print("Stacking two 2D arrays along existing axis:", stack4_result)


Concatenated array along rows: [[3 6]
 [7 4]
 [2 4]
 [1 5]]
Concatenated array along columns: [[3 6 2 4]
 [7 4 1 5]]
Concatenated array by default: [[3 6]
 [7 4]
 [2 4]
 [1 5]]
Concatenated array of different shape: [3 6 7 4 2 4 1 5 1 2]
Concatenated array of different shape: [3 6 7 4 1 2 7 0]
Stacking two 1D arrays vertically: [[1 2 3]
 [4 5 6]]
Stacking two 1D arrays horizontally: [[1 4]
 [2 5]
 [3 6]]
Stacking two 2D arrays along a new axis: [[[3 6]
  [7 4]]

 [[2 4]
  [1 5]]]
Stacking two 2D arrays along existing axis: [[[3 6]
  [2 4]]

 [[7 4]
  [1 5]]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [805]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [806]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [807]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [808]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [828]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01],
       [4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01],
       [8.76389152e-01, 8.94606664e-01, 8.50442114e-02, 3.90547832e-02],
       [1.69830420e-01, 8.78142503e-01, 9.83468338e-02, 4.21107625e-01],
       [9.57889530e-01, 5.33165285e-01, 6.91877114e-01, 3.15515631e-01],
       [6.86500928e-01, 8.34625672e-01, 1.82882773e-02, 7.50144315e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [832]:
np.random.seed(seed=1)
# YOUR CODE HERE

column_mean = np.mean(my_array,axis=0,keepdims=True)
print("Mean of each columns is:",column_mean)

column_std = np.std(my_array,axis=0,keepdims=True)
print("Std. of each column:",column_std)

standardized_array = (my_array - column_mean) / column_std

print('Standardized array shape:', standardized_array.shape)
print('Standardized array:',standardized_array)

Mean of each columns is: [[0.5073657  0.68970888 0.19803242 0.44198268]]
Std. of each column: [[0.28662547 0.25175573 0.20805644 0.23152993]]
Standardized array shape: (10, 4)
Standardized array: [[-0.31519773  0.12160841 -0.95127097 -0.6031622 ]
 [-1.25812201 -2.37281699 -0.05658183 -0.41645566]
 [-0.38586322 -0.59935931  1.06299085  1.05056318]
 [-1.05682671  0.74837842 -0.8201853   0.98684792]
 [-0.31421109 -0.52042131 -0.27706658 -1.05334626]
 [ 1.02356175  1.10644033  0.55461756  1.08124222]
 [ 1.28747613  0.81387534 -0.54306521 -1.74028424]
 [-1.1776179   0.74847798 -0.47912764 -0.09016135]
 [ 1.57182064 -0.62180746  2.37360926 -0.54622331]
 [ 0.62498014  0.5756246  -0.86392014  1.33097969]]


----
#### <span style="color:chocolate">Bonus question:</span> Advanced (20 points)

Consider the following image:

In [833]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by using a border of size 2;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [835]:
# YOUR CODE HERE
crop_border1 = my_image[1:-1, 1:-1]
print("Cropped image with border size 1:",crop_border1)

crop_border2 = my_image[2:-2, 2:-2]
print("Cropped image with border size 2:",crop_border2)

reversed_columns = my_image[:, ::-1]
print("Image with reversed column order:",reversed_columns)
print(reversed_columns)

modified_image = my_image.copy()
modified_image[(modified_image % 2 == 0)] = 0.5
print("Modified image with elements divisible by 2 set to 0.5:",modified_image)

Cropped image with border size 1: [[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
Cropped image with border size 2: [[0.48]]
Image with reversed column order: [[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
Modified image with elements divisible by 2 set to 0.5: [[0.5  0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
